name: check prettier formatting

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "main"

concurrency:
  # Cancel previous jobs
  group: prettier-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: front_end/.nvmrc
          cache: npm
          cache-dependency-path: front_end/package-lock.json
      - name: install deps
        run: npm ci
        working-directory: front_end
      - name: prettier version
        run: npx prettier -v
        working-directory: front_end
      - name: check formatting
        run: npm run format:check
        working-directory: front_end
      - name: check linters
        run: npm run lint
        working-directory: front_end
